version: '3.8'
services:
  ai-dev-team:
    build: .
    volumes:
      - ./projects:/app/projects
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_PORT=5000
      - WORK_DIR=/app/projects
