version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s() - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/ai_dev_team.log
    mode: a
  
  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    mode: a

loggers:
  ai_dev_team:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: no

root:
  level: INFO
  handlers: [console]
